baseURL = "https://thaoprovt1.github.io/ThaoBlog/"
languageCode = "en-us"
title = "ThaoBlog"
theme = "hugo-clarity"
publishDir = "docs"
defaultContentLanguage = "vi"

[pagination]
  pagerSize = 10

[params]
  author = "Thảo 666"
  description = "Blog cá nhân của Thảo — chia sẻ kiến thức về lập trình và công nghệ."
  showReadingTime = true
  showDate = true
  enableMath = false
  mainSections = ["posts"]
  enableSearch = false
  customCSS = ["css/custom.css"]

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "Home - Blogs"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[security]
  [security.sri]
    enable = false
